import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import * as library from "../src/index.ts";
import { showTool } from "../src/tool-operations.ts";
import { authorRows, type AuthorRow } from "../docs/app/utils/authors.ts";
import { collectionFacts, type CollectionFactsData } from "../docs/app/utils/collections.ts";
import { WALK } from "../docs/app/utils/landing.ts";
import { toSample, type LandingSample } from "../docs/app/utils/samples.ts";

const START = "/* generated:landing-fixtures:start */";
const END = "/* generated:landing-fixtures:end */";
const UNDEFINED = "__AGNTN_PUZZLES_LANDING_UNDEFINED_8A77E2B5__";
const TARGET = fileURLToPath(new URL("../docs/app/utils/landing.ts", import.meta.url));
const ROOT = fileURLToPath(new URL("..", import.meta.url));
const FORMATTER = fileURLToPath(new URL("../node_modules/vite-plus/bin/vp", import.meta.url));

type StaticStats = {
  readonly dataVersion: string;
  readonly total: number;
  readonly solved: number;
  readonly unsolved: number;
  readonly claimed: number;
  readonly swept: number;
  readonly expired: number;
  readonly withPubkey: number;
  readonly unsolvedPrize: Readonly<Record<string, number>>;
  readonly totalPrize: Readonly<Record<string, number>>;
};

type LandingFixtures = {
  readonly samples: readonly LandingSample[];
  readonly stats: StaticStats;
  readonly facts: readonly CollectionFactsData[];
  readonly authors: readonly AuthorRow[];
};

type RefreshOptions = {
  readonly check?: boolean;
  readonly targetPath?: string;
  readonly walk?: readonly string[];
};

/** Result of checking or refreshing the generated landing fixtures. */
export type RefreshResult = "current" | "stale" | "updated";

/**
 * Computes every generated landing fixture from one registry snapshot.
 *
 * @param {readonly string[]} walk - Puzzle identifiers selected for the landing.
 * @returns {Promise<LandingFixtures>} Samples, aggregate statistics and collection facts.
 */
export async function buildLandingFixtures(
  walk: readonly string[] = WALK,
): Promise<LandingFixtures> {
  const samples = await Promise.all(
    walk.map(async (id) => {
      const puzzle = await library.requirePuzzle(id);
      const tool = (await showTool(id)).content[0]?.text ?? "";
      return toSample(library, puzzle, tool);
    }),
  );
  const stats = await library.stats();
  return {
    samples,
    stats: {
      dataVersion: await library.dataVersion(),
      total: stats.total,
      solved: stats.solved,
      unsolved: stats.unsolved,
      claimed: stats.claimed,
      swept: stats.swept,
      expired: stats.expired,
      withPubkey: stats.with_pubkey,
      unsolvedPrize: stats.unsolved_prize,
      totalPrize: stats.total_prize,
    },
    facts: (await library.collections()).map(collectionFacts),
    authors: authorRows(await library.authors()),
  };
}

function literal(value: unknown): string {
  const plain = JSON.stringify(value);
  if (plain?.includes(UNDEFINED) === true) {
    throw new Error("Landing fixture data contains the generator's reserved undefined marker");
  }
  const serialized = JSON.stringify(
    value,
    (_key: string, item: unknown): unknown => (item === undefined ? UNDEFINED : item),
    2,
  );
  if (serialized === undefined) {
    throw new Error("Landing fixtures did not serialize to a TypeScript value");
  }
  return serialized
    .replaceAll(JSON.stringify(UNDEFINED), "undefined")
    .replaceAll(/(^|\n)(\s*)"([A-Za-z_$][A-Za-z0-9_$]*)":/gu, "$1$2$3:");
}

function renderGeneratedRegion(fixtures: LandingFixtures, targetPath: string): string {
  const source = `${START}
/**
 * What \`toSample\` gives for the walk, generated by \`pnpm fixtures\` so the page renders before
 * the collections load in the browser.
 */
export const LANDING_STATIC: readonly LandingSample[] = ${literal(fixtures.samples)};

/** \`stats()\` at the landing's data version: the hero figure and the walk. */
export const STATS_STATIC = ${literal(fixtures.stats)} as const;

/** collectionFacts() for every collection: the numbers in the landing rows and the registry panel. */
export const FACTS_STATIC: readonly CollectionFactsData[] = ${literal(fixtures.facts)};

/** authorRows() for every author: the dossier card on the landing before the collections load. */
export const AUTHORS_STATIC: readonly AuthorRow[] = ${literal(fixtures.authors)};
${END}
`;
  return execFileSync(
    process.execPath,
    [FORMATTER, "fmt", "--stdin-filepath", targetPath, "--threads=1"],
    /* vp fmt reads the fmt block of the vite.config.ts at the root it runs from. */
    { cwd: ROOT, encoding: "utf8", input: source },
  );
}

function lineEndingAfter(source: string, offset: number): "\r\n" | "\n" | undefined {
  if (source.startsWith("\r\n", offset)) return "\r\n";
  if (source.startsWith("\n", offset)) return "\n";
  return undefined;
}

function replaceGeneratedRegion(source: string, generated: string, targetPath: string): string {
  const start = source.indexOf(START);
  const end = source.indexOf(END);
  const duplicateStart = source.indexOf(START, start + START.length);
  const duplicateEnd = source.indexOf(END, end + END.length);
  const lineEnding = lineEndingAfter(source, start + START.length);
  const suffixStart = end + END.length + (lineEnding?.length ?? 0);
  if (
    start < 0 ||
    end < start ||
    duplicateStart >= 0 ||
    duplicateEnd >= 0 ||
    lineEnding === undefined ||
    !source.startsWith(lineEnding, end + END.length)
  ) {
    throw new Error(`Expected one generated landing fixture region in ${targetPath}`);
  }
  const normalizedGenerated = generated.replaceAll(/\r?\n/gu, lineEnding);
  return `${source.slice(0, start)}${normalizedGenerated}${source.slice(suffixStart)}`;
}

/**
 * Checks or refreshes the generated fixture region without touching authored content around it.
 *
 * @param {RefreshOptions} options - Check mode, target file and optional walk override.
 * @returns {Promise<RefreshResult>} Whether the target was current, stale or updated.
 */
export async function refreshLandingFixtures(options: RefreshOptions = {}): Promise<RefreshResult> {
  const targetPath = options.targetPath ?? TARGET;
  const source = readFileSync(targetPath, "utf8");
  const fixtures = await buildLandingFixtures(options.walk ?? WALK);
  const next = replaceGeneratedRegion(
    source,
    renderGeneratedRegion(fixtures, targetPath),
    targetPath,
  );
  if (next === source) return "current";
  if (options.check === true) return "stale";
  writeFileSync(targetPath, next);
  return "updated";
}

function parseCheckMode(args: readonly string[]): boolean {
  if (args.length === 0) return false;
  if (args.length === 1 && args[0] === "--check") return true;
  throw new Error("Usage: pnpm fixtures [--check]");
}

async function main(): Promise<void> {
  const check = parseCheckMode(process.argv.slice(2));
  const result = await refreshLandingFixtures({ check });
  if (result === "stale") {
    console.error("Landing fixtures are stale. Run `pnpm fixtures`.");
    process.exitCode = 1;
    return;
  }
  console.log(
    result === "updated" ? "Updated docs/app/utils/landing.ts." : "Landing fixtures are current.",
  );
}

if (process.argv[1] !== undefined && pathToFileURL(process.argv[1]).href === import.meta.url) {
  try {
    await main();
  } catch (error: unknown) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
