export { version } from "./version.ts";

/** Collections load on demand through the registry. Import one directly from `@agntn/puzzles/collections/<key>`. */
export { builtins } from "./collections/index.ts";

export {
  Collection,
  NamedCollection,
  NumericCollection,
  SingletonCollection,
} from "./core/collection.ts";

export {
  ArweavePuzzle,
  arweavePuzzle,
  BitcoinPuzzle,
  bitcoinPuzzle,
  DecredPuzzle,
  decredPuzzle,
  EthereumPuzzle,
  ethereumPuzzle,
  LitecoinPuzzle,
  litecoinPuzzle,
  MoneroPuzzle,
  moneroPuzzle,
  Puzzle,
  Status,
  type AssetLink,
  type PuzzleData,
  type PuzzleSpec,
} from "./core/puzzle.ts";

export {
  AddressKind,
  answer,
  artifact,
  assets,
  bits,
  compressed,
  claim,
  community,
  confirmation,
  decrease,
  derivation,
  encryptedWif,
  fact,
  funding,
  hex,
  HintKind,
  increase,
  Key,
  mini,
  official,
  p2pkh,
  p2sh,
  p2wpkh,
  p2wsh,
  party,
  PartyKind,
  passphrase,
  profile,
  pubkeyReveal,
  PubkeyFormat,
  redeemScript,
  secretOf,
  seed,
  share,
  shares,
  source,
  stage,
  standard,
  sweep,
  TransactionType,
  uncompressed,
  wif,
  type Address,
  type Answer,
  type Artifact,
  type Assets,
  type Confirmation,
  type Entropy,
  type EntropySource,
  type Fact,
  type Hint,
  type HintOptions,
  type KeyData,
  type Party,
  type PartyOptions,
  type Passphrase,
  type Profile,
  type Pubkey,
  type RedeemScript,
  type Secret,
  type Seed,
  type Share,
  type Shares,
  type Stage,
  type Transaction,
  type Wif,
} from "./core/parts.ts";

export {
  collectionKeys,
  collections,
  getCollection,
  hasCollection,
  registerCollection,
  requireCollection,
  type AnyCollection,
  type BuiltinCollections,
  type BuiltinKey,
  type CollectionEntry,
} from "./core/registry.ts";

export {
  all,
  authors,
  collectionSummaries,
  dataset,
  datasetCollections,
  dataVersion,
  get,
  getAuthor,
  getSolver,
  requireAuthor,
  requirePuzzle,
  requireSolver,
  selectPuzzles,
  solvers,
  stats,
  type AuthorEntry,
  type SolveEntry,
  type SolverEntry,
  type CollectionSummary,
  type Dataset,
  type DatasetCollection,
  type PuzzleQuery,
  type Stats,
} from "./core/dataset.ts";

export {
  addressExplorerUrl,
  Chain,
  chainDecimals,
  chainName,
  chains,
  chainSymbol,
  isValidAddress,
  isValidTransactionId,
  parseChain,
  sameAddress,
  transactionExplorerUrl,
} from "./core/chains.ts";

export {
  BalanceError,
  BalanceProviderError,
  InvalidAddressError,
  UnsupportedChainError,
  type BalanceOptions,
} from "./core/balance.ts";

export { Balance } from "./core/types.ts";

export {
  InvalidArgumentError,
  PuzzleNotFoundError,
  PuzzlesError,
  UnknownAuthorError,
  UnknownCollectionError,
  UnknownSolverError,
} from "./core/errors.ts";

export {
  verify,
  type VerifyFailure,
  type VerifyResult,
  type VerifySuccess,
} from "./core/verify.ts";
